image: alpine:latest

pages:
  stage: deploy
  script:
  - cd docs
  - pip install -r requirements.txt
  - make html
  - cp build/html/ ../public
  artifacts:
    paths:
    - public
  only:
  - master
