image: python:2.7-alpine

pages:
  stage: deploy
  script:
  - cd docs
  - pip install -r requirements.txt
  - sphinx-build -M html "source" "build" 
  - cp source/my_theme.css build/html/_static/css
  - cp -r build/html/ ../public
  artifacts:
    paths:
    - public
  only:
  - master
